### ISSUE TITLE
Mismatch lines number and line code

### ISSUE THREAD

**Issue by Taluu** [dflydev/embed-github-gist#9]
Hi,

The plugin is awesome, but I have some problem with the rendered result... It is probably a issue from the github's gist system, but still, I report it here if it is maybe an issue from your plugin.

The lines number and the code does not match. I have a live example right here : http://baptiste.clavié.net/labo/ne-pas-se-moquer-des-mocks/ and the gist is here : https://gist.github.com/4407655

Any idea ?

Thanks for your awesome work. I picked this plugin because I know the quality brought by the work you're doing :)

**Comment by Taluu** [comment]
Nevermind, it does seems to be an issue from the gists system...

**Comment by Taluu** [comment]
For those who want to settle the problem, you will need to add a custom CSS to your wordpress theme :

``` css
td.line_numbers span {
  font-size: 12px !important;
  line-height: 1.5em !important;
}
```
